/* global Nimiq */
/* global PolygonKey */
/* global PolygonConstants */
/* global Dummy */

describe('BitcoinKey', () => {
    it('can derive an address', () => {
        const key = new Key(Dummy.secrets[0]);
        const polyKey = new PolygonKey(key);
        // Address generated by https://iancoleman.io/bip39/
        const address = '0x1A225DEc2287A08258F9A77c526faCa8e3607eA0';
        expect(polyKey.deriveAddress(PolygonConstants.DEFAULT_DERIVATION_PATH)).toEqual(address);
    });

    it('can sign a transaction', () => {
        // const mnemonic = 'rib dream attitude script click hope aisle orphan flat early athlete twelve toy sell cigar ugly drink flavor power common devote love relax capable';
        // const entropy = Nimiq.MnemonicUtils.mnemonicToEntropy(mnemonic);
        // const key = new Key(entropy);
        // const btcKey = new BitcoinKey(key);

        // const inputs = [{
        //     hash: '1683f5639e614ccd11b6542a502eb31ed0a76a04809d56c2ecbca5335c67eb32',
        //     index: 1, // Our output was the second in the input tx
        //     witnessUtxo: {
        //         script: BitcoinJS.Buffer.from('001484eb9bcbd90ce7d3360992259e4b9b818215a960', 'hex'),
        //         value: 1000000,
        //     },
        // }, {
        //     hash: '18d7a602b06c9613412bc935c5fbe7a22ff4e670bc176f75fadbdf2fb9940b5d',
        //     index: 0, // Our output was the first in the input tx
        //     witnessUtxo: {
        //         script: BitcoinJS.Buffer.from('001484eb9bcbd90ce7d3360992259e4b9b818215a960', 'hex'),
        //         value: 4983992,
        //     },
        // }, {
        //     hash: '550bce13e303ace1c45f5f2112a3098c62c08b132a7042f6b7b085102051c082',
        //     index: 1, // Our output was the second in the input tx
        //     witnessUtxo: {
        //         script: BitcoinJS.Buffer.from('001484eb9bcbd90ce7d3360992259e4b9b818215a960', 'hex'),
        //         value: 1000000,
        //     },
        // }, {
        //     hash: '5fedaef5229799e18e351f76395bb7411e56da2291f99905e75dc72850ce2fdf',
        //     index: 0, // Our output was the first in the input tx
        //     witnessUtxo: {
        //         script: BitcoinJS.Buffer.from('001484eb9bcbd90ce7d3360992259e4b9b818215a960', 'hex'),
        //         value: 1000000,
        //     },
        // }, {
        //     hash: '891adf338c070c5512fc28a9d77d648a8f25ad0d63e742b3fb0605eb9124aee8',
        //     index: 1, // Our output was the second in the input tx
        //     witnessUtxo: {
        //         script: BitcoinJS.Buffer.from('001484eb9bcbd90ce7d3360992259e4b9b818215a960', 'hex'),
        //         value: 22000,
        //     },
        // }, {
        //     hash: '738b5c17758131b22d560ad6417defb830c3940bfc4074d0414b44798e880747',
        //     index: 25, // Our output was the 26th in the input tx
        //     witnessUtxo: {
        //         script: BitcoinJS.Buffer.from('001484eb9bcbd90ce7d3360992259e4b9b818215a960', 'hex'),
        //         value: 27738766,
        //     },
        // }].sort((input1, input2) => {
        //     if (input1.hash !== input2.hash) return input1.hash < input2.hash ? -1 : 1;
        //     return input1.index - input2.index;
        // });

        // const sum = inputs.reduce((sum, input) => sum + input.witnessUtxo.value, 0);
        // const amount = Math.round(sum / 2);

        // const paths = [`${BitcoinConstants.ACCOUNT_DERIVATION_PATH.BIP84.TEST}/0/0`];

        // const outputs = [{
        //     address: 'tb1qm37aps59r86g79jg5xh8ecgfqfncv92wzfyyx7',
        //     value: amount,
        // }, {
        //     address: 'tb1qxvrezy277f2035kasl39pls454yjwtgqkfv05z',
        //     value: sum - amount - 481, // 481 is the fee
        // }].sort((output1, output2) => {
        //     return (output1.value - output2.value) || (output1.address < output2.address ? -1 : 1);
        // });

        // const psbt = new BitcoinJS.Psbt({ network: BitcoinJS.networks.testnet });

        // // @ts-ignore Argument of type 'import("...").Buffer' is not assignable to parameter of type 'Buffer'.
        // psbt.addInputs(inputs);
        // psbt.addOutputs(outputs);

        // btcKey.sign(paths, psbt);

        // psbt.finalizeAllInputs();

        // const tx = psbt.extractTransaction();

        // expect(tx.toHex()).toEqual(
        //     '0200000000010632eb675c33a5bcecc2569d80046aa7d01eb32e502a54b611cd4c619e63f583160100000000ffffffff5d0b94b92fdfdbfa756f17bc70e6f42fa2e7fbc535c92b4113966cb002a6d7180000000000ffffffff82c051201085b0b7f642702a138bc0628c09a312215f5fc4e1ac03e313ce0b550100000000ffffffffdf2fce5028c75de70599f99122da561e41b75b39761f358ee1999722f5aeed5f0000000000ffffffff4707888e79444b41d07440fc0b94c330b8ef7d41d60a562db2318175175c8b731900000000ffffffffe8ae2491eb0506fbb342e7630dad258f8a647dd7a928fc12550c078c33df1a890100000000ffffffff021ab4100100000000160014330791115ef254f8d2dd87e250fe15a549272d00fbb5100100000000160014dc7dd0c28519f48f1648a1ae7ce109026786154e0247304402204220932488f18220acff985ef6a58c63634327d2d794ed51325c1a01ac882f4b02204187151ade1bc52e2fa640b4ec097b4fa8fe9e6bbd1cc5b208e5429a4525b1df01210263324a046eb0c4a110488d6a61fcdfae2fcefa1ca6123ddc12c1fdb15380540002473044022100d325fd9d32dc06083afdb929ce4774fba8767065d7d51c7e4fcc9533cb2df129021f2f3f5a0e4241aacd6ac185f28dd9b96ee3f15b2e60eee129c477cccf6d86a401210263324a046eb0c4a110488d6a61fcdfae2fcefa1ca6123ddc12c1fdb153805400024830450221009531de6c2719863e6cd62c1c4d906e1e9a96a558911ed9fc0ca705c7112c9ce302203c0686c6ebaa286401676c826b8fe7d9f7d1038f07486c20d74ee91a75f110b301210263324a046eb0c4a110488d6a61fcdfae2fcefa1ca6123ddc12c1fdb1538054000247304402201855311c8ddb69d4d1f01066dd5b50383aec5bcd5bf6e5ed292fa01de2fda327022068ab1fe7023cfe9624fddfc11c1f48c63cb826786a6d1e992decc3ec2f81a13101210263324a046eb0c4a110488d6a61fcdfae2fcefa1ca6123ddc12c1fdb15380540002483045022100f615f597bfe84c41e9e64e0aa58c10e1046350795a788ba6582c7e64e98045e1022066c2f75b3c6e6a4becde4026a12fa2a94b8112671b7eecdf1240e995f355e31e01210263324a046eb0c4a110488d6a61fcdfae2fcefa1ca6123ddc12c1fdb1538054000247304402205b28f1cfe0be1212254148f251a8d42dd3031c1a6a51f3ea31d8f912c7d2057702205c7fa92aac1b36fe26688aa465b9a45f588b546438b9f2748298dbcd4520431101210263324a046eb0c4a110488d6a61fcdfae2fcefa1ca6123ddc12c1fdb15380540000000000'
        // );
    });
});
