/* eslint-disable max-len */
const PolygonContractABIs = { // eslint-disable-line no-unused-vars
    USDC_CONTRACT_ABI: [
        // 'event Approval(address indexed owner, address indexed spender, uint256 value)',
        // 'event AuthorizationCanceled(address indexed authorizer, bytes32 indexed nonce)',
        // 'event AuthorizationUsed(address indexed authorizer, bytes32 indexed nonce)',
        // 'event Blacklisted(address indexed account)',
        // 'event MetaTransactionExecuted(address userAddress, address relayerAddress, bytes functionSignature)',
        // 'event Pause()',
        // 'event RescuerChanged(address indexed newRescuer)',
        // 'event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)',
        // 'event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)',
        // 'event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)',
        // 'event Transfer(address indexed from, address indexed to, uint256 value)',
        // 'event UnBlacklisted(address indexed account)',
        // 'event Unpause()',
        // 'function APPROVE_WITH_AUTHORIZATION_TYPEHASH() view returns (bytes32)',
        // 'function BLACKLISTER_ROLE() view returns (bytes32)',
        // 'function CANCEL_AUTHORIZATION_TYPEHASH() view returns (bytes32)',
        // 'function DECREASE_ALLOWANCE_WITH_AUTHORIZATION_TYPEHASH() view returns (bytes32)',
        // 'function DEFAULT_ADMIN_ROLE() view returns (bytes32)',
        // 'function DEPOSITOR_ROLE() view returns (bytes32)',
        // 'function DOMAIN_SEPARATOR() view returns (bytes32)',
        // 'function EIP712_VERSION() view returns (string)',
        // 'function INCREASE_ALLOWANCE_WITH_AUTHORIZATION_TYPEHASH() view returns (bytes32)',
        // 'function META_TRANSACTION_TYPEHASH() view returns (bytes32)',
        // 'function PAUSER_ROLE() view returns (bytes32)',
        // 'function PERMIT_TYPEHASH() view returns (bytes32)',
        // 'function RESCUER_ROLE() view returns (bytes32)',
        // 'function TRANSFER_WITH_AUTHORIZATION_TYPEHASH() view returns (bytes32)',
        // 'function WITHDRAW_WITH_AUTHORIZATION_TYPEHASH() view returns (bytes32)',
        // 'function allowance(address owner, address spender) view returns (uint256)',
        'function approve(address spender, uint256 amount) returns (bool)',
        // 'function approveWithAuthorization(address owner, address spender, uint256 value, uint256 validAfter, uint256 validBefore, bytes32 nonce, uint8 v, bytes32 r, bytes32 s)',
        // 'function authorizationState(address authorizer, bytes32 nonce) view returns (uint8)',
        // 'function balanceOf(address account) view returns (uint256)',
        // 'function blacklist(address account)',
        // 'function blacklisters() view returns (address[])',
        // 'function cancelAuthorization(address authorizer, bytes32 nonce, uint8 v, bytes32 r, bytes32 s)',
        // 'function decimals() view returns (uint8)',
        // 'function decreaseAllowance(address spender, uint256 subtractedValue) returns (bool)',
        // 'function decreaseAllowanceWithAuthorization(address owner, address spender, uint256 decrement, uint256 validAfter, uint256 validBefore, bytes32 nonce, uint8 v, bytes32 r, bytes32 s)',
        // 'function deposit(address user, bytes depositData)',
        // 'function executeMetaTransaction(address userAddress, bytes functionSignature, bytes32 sigR, bytes32 sigS, uint8 sigV) payable returns (bytes)',
        // 'function getRoleAdmin(bytes32 role) view returns (bytes32)',
        // 'function getRoleMember(bytes32 role, uint256 index) view returns (address)',
        // 'function getRoleMemberCount(bytes32 role) view returns (uint256)',
        // 'function grantRole(bytes32 role, address account)',
        // 'function hasRole(bytes32 role, address account) view returns (bool)',
        // 'function increaseAllowance(address spender, uint256 addedValue) returns (bool)',
        // 'function increaseAllowanceWithAuthorization(address owner, address spender, uint256 increment, uint256 validAfter, uint256 validBefore, bytes32 nonce, uint8 v, bytes32 r, bytes32 s)',
        // 'function initialize(string newName, string newSymbol, uint8 newDecimals, address childChainManager)',
        // 'function initialized() view returns (bool)',
        // 'function isBlacklisted(address account) view returns (bool)',
        // 'function name() view returns (string)',
        // 'function nonces(address owner) view returns (uint256)',
        // 'function pause()',
        // 'function paused() view returns (bool)',
        // 'function pausers() view returns (address[])',
        // 'function permit(address owner, address spender, uint256 value, uint256 deadline, uint8 v, bytes32 r, bytes32 s)',
        // 'function renounceRole(bytes32 role, address account)',
        // 'function rescueERC20(address tokenContract, address to, uint256 amount)',
        // 'function rescuers() view returns (address[])',
        // 'function revokeRole(bytes32 role, address account)',
        // 'function symbol() view returns (string)',
        // 'function totalSupply() view returns (uint256)',
        // 'function transfer(address recipient, uint256 amount) returns (bool)',
        // 'function transferFrom(address sender, address recipient, uint256 amount) returns (bool)',
        // 'function transferWithAuthorization(address from, address to, uint256 value, uint256 validAfter, uint256 validBefore, bytes32 nonce, uint8 v, bytes32 r, bytes32 s)',
        // 'function unBlacklist(address account)',
        // 'function unpause()',
        // 'function updateMetadata(string newName, string newSymbol)',
        // 'function withdraw(uint256 amount)',
        // 'function withdrawWithAuthorization(address owner, uint256 value, uint256 validAfter, uint256 validBefore, bytes32 nonce, uint8 v, bytes32 r, bytes32 s)',
    ],

    USDC_TRANSFER_CONTRACT_ABI: [
        // 'constructor()',
        // 'event DomainRegistered(bytes32 indexed domainSeparator, bytes domainValue)',
        // 'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
        // 'event RequestTypeRegistered(bytes32 indexed typeHash, string typeStr)',
        // 'function EIP712_DOMAIN_TYPE() view returns (string)',
        // 'function deposits(address) view returns (uint256)',
        // 'function domains(bytes32) view returns (bool)',
        // 'function execute(tuple(address from, address to, uint256 value, uint256 gas, uint256 nonce, bytes data, uint256 validUntil) request, bytes32 domainSeparator, bytes32 requestTypeHash, bytes suffixData, bytes signature) payable returns (bool success, bytes ret)',
        // 'function getGasAndDataLimits() view returns (tuple(uint256 acceptanceBudget, uint256 preRelayedCallGasLimit, uint256 postRelayedCallGasLimit, uint256 calldataSizeLimit) limits)',
        // 'function getHubAddr() view returns (address)',
        // 'function getMinimumRelayFee(tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData) view returns (uint256 amount)',
        // 'function getNonce(address from) view returns (uint256)',
        // 'function getRelayHubDeposit() view returns (uint256)',
        // 'function getRequiredRelayFee(tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData, bytes4 methodId) view returns (uint256 amount)',
        // 'function getRequiredRelayGas(bytes4 methodId) view returns (uint256 gas)',
        // 'function isTrustedForwarder(address forwarder) view returns (bool)',
        // 'function owner() view returns (address)',
        // 'function postRelayedCall(bytes context, bool success, uint256 gasUseWithoutPost, tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData)',
        // 'function preRelayedCall(tuple(tuple(address from, address to, uint256 value, uint256 gas, uint256 nonce, bytes data, uint256 validUntil) request, tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData) relayRequest, bytes signature, bytes approvalData, uint256 maxPossibleGas) returns (bytes context, bool revertOnRecipientRevert)',
        // 'function registerDomainSeparator(string name, string version)',
        // 'function registerRequestType(string typeName, string typeSuffix)',
        // 'function registerToken(address token, address pool)',
        // 'function registeredTokenPool(address) view returns (address)',
        // 'function registeredTokenPoolFee(address token) view returns (uint24 fee)',
        // 'function renounceOwnership()',
        // 'function requiredRelayGas() view returns (uint256)',
        // 'function setGasAndDataLimits(tuple(uint256 acceptanceBudget, uint256 preRelayedCallGasLimit, uint256 postRelayedCallGasLimit, uint256 calldataSizeLimit) limits)',
        // 'function setMaxRequiredRelayGas(uint256 gas)',
        // 'function setRelayHub(address hub)',
        // 'function setRequiredRelayGas(bytes4 methodId, uint256 gas)',
        // 'function setWrappedChainToken(address _wrappedChainToken)',
        'function transfer(address token, uint256 amount, address target, uint256 fee)',
        // 'function transferOwnership(address newOwner)',
        'function transferWithApproval(address token, uint256 amount, address target, uint256 fee, uint256 approval, bytes32 sigR, bytes32 sigS, uint8 sigV)',
        // 'function trustedForwarder() view returns (address forwarder)',
        // 'function typeHashes(bytes32) view returns (bool)',
        // 'function uniswapV3SwapCallback(int256 amount0Delta, int256 amount1Delta, bytes _data)',
        // 'function unregisterToken(address token)',
        // 'function verify(tuple(address from, address to, uint256 value, uint256 gas, uint256 nonce, bytes data, uint256 validUntil) forwardRequest, bytes32 domainSeparator, bytes32 requestTypeHash, bytes suffixData, bytes signature) view',
        // 'function versionPaymaster() view returns (string)',
        // 'function versionRecipient() view returns (string)',
        // 'function withdraw(uint256 amount, address target)',
        // 'function withdrawRelayHubDeposit(uint256 amount, address target)',
        // 'function withdrawToken(address token, uint256 amount, address target)',
        // 'function wrappedChainToken() view returns (address)',
    ],

    USDC_HTLC_CONTRACT_ABI: [
        // 'constructor()',
        // 'event DomainRegistered(bytes32 indexed domainSeparator, bytes domainValue)',
        // 'event Open(bytes32 id, address token, uint256 amount, address recipient, bytes32 hash, uint256 timeout)',
        // 'event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)',
        // 'event Redeem(bytes32 id, bytes32 secret)',
        // 'event Refund(bytes32 id)',
        // 'event RequestTypeRegistered(bytes32 indexed typeHash, string typeStr)',
        // 'function CALLDATA_SIZE_LIMIT() view returns (uint256)',
        // 'function EIP712_DOMAIN_TYPE() view returns (string)',
        // 'function deposits(address) view returns (uint256)',
        // 'function domains(bytes32) view returns (bool)',
        // 'function execute(tuple(address from, address to, uint256 value, uint256 gas, uint256 nonce, bytes data, uint256 validUntil) request, bytes32 domainSeparator, bytes32 requestTypeHash, bytes suffixData, bytes signature) payable returns (bool success, bytes ret)',
        // 'function getGasAndDataLimits() view returns (tuple(uint256 acceptanceBudget, uint256 preRelayedCallGasLimit, uint256 postRelayedCallGasLimit, uint256 calldataSizeLimit) limits)',
        // 'function getHubAddr() view returns (address)',
        // 'function getMinimumRelayFee(tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData) view returns (uint256 amount)',
        // 'function getNonce(address from) view returns (uint256)',
        // 'function getRelayHubDeposit() view returns (uint256)',
        // 'function htlcs(bytes32) view returns (address token, uint256 amount, address refund, address recipient, bytes32 hash, uint256 timeout)',
        // 'function isTrustedForwarder(address forwarder) view returns (bool)',
        'function open(bytes32 id, address token, uint256 amount, address refundAddress, address recipientAddress, bytes32 hash, uint256 timeout, uint256 fee, uint256 chainTokenFee)',
        'function openWithApproval(bytes32 id, address token, uint256 amount, address refundAddress, address recipientAddress, bytes32 hash, uint256 timeout, uint256 fee, uint256 chainTokenFee, uint256 approval, bytes32 sigR, bytes32 sigS, uint8 sigV)',
        // 'function owner() view returns (address)',
        // 'function postRelayedCall(bytes context, bool success, uint256 gasUseWithoutPost, tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData)',
        // 'function preApprovedGasDiscount() view returns (uint256)',
        // 'function preRelayedCall(tuple(tuple(address from, address to, uint256 value, uint256 gas, uint256 nonce, bytes data, uint256 validUntil) request, tuple(uint256 gasPrice, uint256 pctRelayFee, uint256 baseRelayFee, address relayWorker, address paymaster, address forwarder, bytes paymasterData, uint256 clientId) relayData) relayRequest, bytes signature, bytes approvalData, uint256 maxPossibleGas) returns (bytes context, bool revertOnRecipientRevert)',
        'function redeem(bytes32 id, address target, bytes32 secret, uint256 fee, uint256 chainTokenFee)',
        'function redeemWithSecretInData(bytes32 id, address target, uint256 fee, uint256 chainTokenFee)',
        'function refund(bytes32 id, address target, uint256 fee, uint256 chainTokenFee)',
        // 'function registerDomainSeparator(string name, string version)',
        // 'function registerRequestType(string typeName, string typeSuffix)',
        // 'function registerToken(address token, uint24 poolFee)',
        // 'function registeredTokenPoolFee(address) view returns (uint24)',
        // 'function renounceOwnership()',
        // 'function requiredRelayGas() view returns (uint256 amount)',
        // 'function setRelayHub(address hub)',
        // 'function setSwapRouter(address _swapRouter)',
        // 'function setWrappedChainToken(address _wrappedChainToken)',
        // 'function swapRouter() view returns (address)',
        // 'function transferOwnership(address newOwner)',
        // 'function trustedForwarder() view returns (address forwarder)',
        // 'function typeHashes(bytes32) view returns (bool)',
        // 'function unregisterToken(address token)',
        // 'function updatePreApprovedGasDiscount(uint256 _preApprovedGasDiscount)',
        // 'function updateRelayGas(uint256 preRelayedCallGasLimit, uint256 postRelayedCallGasLimit, uint256 executeCallGasLimit, uint256 relayOverhead)',
        // 'function verify(tuple(address from, address to, uint256 value, uint256 gas, uint256 nonce, bytes data, uint256 validUntil) forwardRequest, bytes32 domainSeparator, bytes32 requestTypeHash, bytes suffixData, bytes signature) view',
        // 'function versionPaymaster() view returns (string)',
        // 'function versionRecipient() view returns (string)',
        // 'function withdraw(uint256 amount, address target)',
        // 'function withdrawRelayHubDeposit(uint256 amount, address target)',
        // 'function wrappedChainToken() view returns (address)',
    ],
};
/* eslint-enable max-len */
